#!/usr/bin/env bash

mkdir -pv archive

pushd archive > /dev/null

wget -nc --input-file=../wget-sources --continue

popd > /dev/null

mkdir -pv sources

pushd sources > /dev/null

GIT_SOURCES=$(cat ../git-sources)

for URL in $GIT_SOURCES; do
    REPO=$(printf "%s" $URL | sed "s/^.*\/\(.*\)$/\1/")
    if [ ! -e $REPO ]; then
        git clone $URL
    else
        printf "%s already exists.\n" $REPO
    fi
done

popd > /dev/null


