#!/usr/bin/env bash

mkdir -pv rootfs

pushd rootfs

mkdir -pv ./{etc,var} ./usr/{bin,lib,sbin}
for i in bin lib sbin; do
  ln -sv ./usr/$i ./$i
done
mkdir -pv ./lib64

mkdir -pv ./{dev,proc,sys,run}
mkdir -pv ./{boot,home,mnt,opt,srv}
mkdir -pv ./etc/{opt,sysconfig}
mkdir -pv ./lib/firmware
mkdir -pv ./media/{floppy,cdrom}
mkdir -pv ./usr/{,local/}{include,src}
mkdir -pv ./usr/local/{bin,lib,sbin}
mkdir -pv ./usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -pv ./usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv ./usr/{,local/}share/man/man{1..8}
mkdir -pv ./var/{cache,local,log,mail,opt,spool}
mkdir -pv ./var/lib/{color,misc,locate}

ln -sfv ./run ./var/run
ln -sfv ./run/lock ./var/lock

install -dv -m 0750 ./root
install -dv -m 1777 ./tmp ./var/tmp

popd
