#!/usr/bin/env bash

mkdir -pv isoimage 

for SCRIPT in ./build-scripts/[0-9][0-9]*; do
    COMMANDS=$(cat $SCRIPT)
    pushd $(echo "./sources/$(basename $SCRIPT | sed "s/[0-9][0-9]-\(.*\)/\1/"  )*") > /dev/null
    printf "%s" "${COMMANDS}" | bash
    popd > /dev/null
done
