#!/usr/bin/env bash

pushd ./isoimage

pwd

# Packaging of rootfs into compressed archive
find ../rootfs | cpio -R root:root -H newc -o | gzip > ./rootfs.gz

# Packaging of system into iso image
xorriso \
  -as mkisofs \
  -o ../linux-for-learners.iso \
  -b isolinux.bin \
  -c boot.cat \
  -no-emul-boot \
  -boot-load-size 4 \
  -boot-info-table \
  ./

popd
