#!/usr/bin/env bash

if ! [[ -e Makefile ]]; then
    ./configure --bindir=$(realpath ../../rootfs/bin)           \
                --mandir=$(realpath ../../rootfs/usr/share/man) \
                --enable-static
fi

make
make install
ln -svr ../../rootfs/usr/bin/dash ../../rootfs/usr/bin/sh

