#!/usr/bin/env bash

if ! [[ -e Makefile.local ]]; then
    ./configure
fi

make LDFLAGS='-static'     \
     DESTDIR=../../rootfs  \
     BINDIR=/usr/bin       \
     SBINDIR=/usr/sbin     \
     MANDIR=/usr/share/man install

