#!/usr/bin/env bash

git checkout 3c88778

git restore .

sed -i '3 a #include <sys/sysmacros.h>' ./libutil/tty.c
sed -i '3 a #include <sys/sysmacros.h>' ./mknod.c
sed -i '3 a #include <sys/sysmacros.h>' ./mountpoint.c
sed -i '3 a #include <sys/sysmacros.h>' ./stat.c

make DESTDIR=../../rootfs PREFIX=/usr LDFLAGS='-static' ubase-box-install
