#!/usr/bin/env bash

if ! [[ -e ubase-box ]]; then
    git checkout 3c88778

    git restore ./libutil/tty.c \
                ./mknod.c       \
                ./mountpoint.c  \
                ./stat.c

    sed -i '3 a #include <sys/sysmacros.h>' ./libutil/tty.c
    sed -i '3 a #include <sys/sysmacros.h>' ./mknod.c
    sed -i '3 a #include <sys/sysmacros.h>' ./mountpoint.c
    sed -i '3 a #include <sys/sysmacros.h>' ./stat.c
fi

make DESTDIR=../../rootfs PREFIX=/usr LDFLAGS='-static' ubase-box-install

