#!/usr/bin/env bash

if ! [[ -e config.mak ]]; then
    sed -i \
        -e '977c//        if (output_type != TCC_OUTPUT_DLL)' \
        -e '978c//            tcc_add_crt(s, "crt1.o");'      \
        -e '979c//        tcc_add_crt(s, "crti.o");'          \
        -e '980c    tcc_add_crt(s, "crt0.o");}'               \
        libtcc.c

    sed -i \
        -e '1205c//        if (s1->output_type != TCC_OUTPUT_MEMORY)' \
        -e '1206c//            tcc_add_crt(s1, "crtn.o");'            \
        tccelf.c

    ./configure --cc="gcc -static"                                 \
                --enable-static                                    \
                --prefix=/usr                                      \
                --docdir=/usr/share                                \
                --libdir=/usr/lib                                  \
                --sysincludepaths=/opt/diet/include:/usr/include   \
                --libpaths=/opt/diet/lib-x86_64:/usr/lib           \
                --crtprefix=/opt/diet/lib-x86_64
fi

make
make tcc.1
cp libtcc.a libtcc1.a

PREFIX=../../rootfs/usr
DOCDIR=../../rootfs/usr/share

mkdir -p "$PREFIX/bin" && cp -vf tcc "$PREFIX/bin"
mkdir -p "$PREFIX/lib/tcc" && cp -vf libtcc1.a "$PREFIX/lib/tcc"
mkdir -p "$PREFIX/lib/tcc/include" && cp -vf ./include/*.h ./tcclib.h "$PREFIX/lib/tcc/include"
mkdir -p "$PREFIX/lib" && cp -vf libtcc.a "$PREFIX/lib"
mkdir -p "$PREFIX/include" && cp -vf ./libtcc.h "$PREFIX/include"
mkdir -p "$DOCDIR/man/man1" && cp -vf tcc.1 "$DOCDIR/man/man1"

