#!/usr/bin/env bash

sed -e 's:#ENCRYPT_METHOD DES:ENCRYPT_METHOD SHA512:' \
    -e 's:/var/spool/mail:/var/mail:'                 \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                \
    -i etc/login.defs

if ! [[ -e Makefile ]]; then
    ./configure --prefix=/usr                    \
                --sysconfdir=/etc                \
                --disable-shared                 \
                --enable-static                  \
                --with-group-name-max-length=32  \
                LDFLAGS=--static
fi

make DESTDIR=$(realpath ../../rootfs) install

