#!/usr/bin/env bash

# Gnulib patches

sed -e '34s/ftrylockfile/EOF_SEEN/' \
    -e '141s/ftrylockfile/EOF_SEEN/' \
    -i ./lib/fflush.c

sed -e '64s/ftrylockfile/EOF_SEEN/' \
    -i ./lib/fpurge.c

sed -e '34s/ftrylockfile/EOF_SEEN/' \
    -i ./lib/freading.c

sed -e '45s/ftrylockfile/EOF_SEEN/' \
    -e '111s/ftrylockfile/EOF_SEEN/' \
    -i ./lib/fseeko.c

sed -e '20a /* Glibc 2.28 made _IO_IN_BACKUP private.  For now, work around this \
   problem by defining it ourselves.  FIXME: Do not rely on glibc \
   internals.  */ \
#if !defined _IO_IN_BACKUP && defined _IO_EOF_SEEN \
# define _IO_IN_BACKUP 0x100 \
#endif' \
    -i ./lib/stdio-impl.h

sed -e '738s/^\(\/\*\)*/\/*/' \
    -e '738s/\(\*\/\)*$/*\//' \
    -i ./lib/stdio.in.h

# Libparted patches

sed -e '/#include <sys\/sysmacros.h>/d' \
    -e '24a #include <sys/sysmacros.h>' \
    -i ./libparted/arch/linux.c

# Configuration and make

if ! [[ -e Makefile ]]; then
    ./configure --prefix=/usr             \
                --disable-device-mapper   \
                --disable-shared          \
                --enable-static           \
                --without-readline        \
                --disable-Werror          \
                --disable-dynamic-loading \
                LDFLAGS=--static
fi

make DESTDIR=$(realpath ../../rootfs) install

