#!/bin/sh

ROOT=./rootfs

# Mounting of virtual kernel filesystems
mount -o bind /dev $ROOT/dev
mount -o bind /dev/pts $ROOT/dev/pts
mount -t proc proc $ROOT/proc
mount -t sysfs /sys $ROOT/sys

# Entering chroot
chroot $ROOT /bin/login

# Cleanup
umount $ROOT/dev/pts
umount $ROOT/dev
umount $ROOT/sys
umount $ROOT/proc
