#!/usr/bin/env bash

mkdir -pv archive

pushd archive > /dev/null

# Acquisition of compressed archives

wget -nc --input-file=../src-lists/wget-sources --continue

popd > /dev/null

mkdir -pv sources

pushd sources > /dev/null

# Acquisition of git repositories

GIT_SOURCES=$(cat ../src-lists/git-sources)

for URL in $GIT_SOURCES; do
    REPO=$(printf "%s" $URL | sed "s/^.*\/\(.*\)$/\1/")
    if [ ! -e $REPO ]; then
        git clone $URL
    else
        printf "%s already exists.\n" $REPO
    fi
done

popd > /dev/null

