#!/usr/bin/env bash

pushd sources > /dev/null

# Extraction of each archive from the archive directory
# into the sources directory

for ARCHIVE in ../archive/*; do
    PKG_NAME_REGEX="$(basename $ARCHIVE | sed 's/\(.*\)-.*/\1/')*"
    PKG_NAME=$(find . -maxdepth 1 -type d -name $PKG_NAME_REGEX)
    if [[ -z $PKG_NAME ]]; then
        tar -xvf $ARCHIVE
    fi
done

popd > /dev/null

