#!/usr/bin/env bash

mkdir -pv isoimage 

# Iteration over the scripts in pkg-scripts and execution of each script in its
# corresponding directory in sources

for SCRIPT in ./pkg-scripts/[0-9][0-9]*; do
    COMMANDS=$(cat $SCRIPT)
    pushd $(echo "./sources/$(basename $SCRIPT | sed "s/[0-9][0-9]-\(.*\)/\1/"  )*") > /dev/null
    printf "%s" "${COMMANDS}" | bash
    popd > /dev/null
done

