#!/usr/bin/env bash

./configure --bindir=$(realpath ../../rootfs/bin) \
            --mandir=$(realpath ../../rootfs/usr/share/man) \
            --enable-static

make
make install
ln -svr ../../rootfs/usr/bin/dash ../../rootfs/usr/bin/sh
