#!/usr/bin/env bash

pushd rootfs > /dev/null

# Packaging of rootfs into compressed archive
find . | cpio -R root:root -H newc -o | gzip > ../isoimage/rootfs.gz

popd > /dev/null

pushd isoimage > /dev/null

# Packaging of system into iso image
xorriso \
  -as mkisofs \
  -o ../linux-for-learners.iso \
  -b isolinux.bin \
  -c boot.cat \
  -no-emul-boot \
  -boot-load-size 4 \
  -boot-info-table \
  ./

popd > /dev/null

