#!/usr/bin/env bash
./configure --prefix=$(realpath "../../rootfs/usr")  \
            --disable-setuid                         \
            --enable-cache-owner=bin                 \
            --with-browser=/usr/bin/lynx             \
            --with-vgrind=/usr/bin/vgrind            \
            --with-grap=/usr/bin/grap                \
            --with-systemdtmpfilesdir=               \
            --with-systemdsystemunitdir=
make LDFLAGS='-static' install
